iadvize/documentation

Documentation.md
- Webhook doc under API section (to be approved by Seb&Team)
- webhook doc of developer platform under Build section  (to be approved by Seb&Team)
- Update of REST API typo & structure to fit the position of output examples according to titles  (to be approved by Seb&Team)
=> Update documentation content and structure

Documentation.md
We have undesired HTML tags who break the documentation rendering
=> fix(removeHTMLTags) : undesired p and b

README.md
Ajout d'un readme de base pour le repo
=> feat(readme) : write a first good readme

.github/PULL_REQUEST_TEMPLATE.md, Documentation.md
> Ticket link [INT-29](https://iadvize.atlassian.net/browse/INT-29)
Add payloads for webhook
=> INT-29 - Add payloads for webhook

Documentation.md
> Ticket link [] https://iadvize.atlassian.net/browse/INT-655
=> INT-655 Added PUSH API documentation

Documentation.md
=> Update documentation date

Documentation.md
> Ticket link [INT-736](https://iadvize.atlassian.net/browse/INT-736)
Conversation closed unification
=> INT-736 - Conversation closed unification

Documentation.md
=> INT-745 : visitor profile

.gitignore, Documentation.md
https://iadvize.atlassian.net/browse/INT-766
=> Int 766 url validation

Documentation.md
> Ticket link [INT-346](https://iadvize.atlassian.net/browse/INT-346)
Add headers iAdvize to sign webhook request with hmac_256 alghorithm
```
X-Iadvize-Signature: sha256=31ca7c1ae78abb16d50878af6caaba753cc773d73e145f361c9c85f5e166f74b
X-iAdvize-CorrelationId: dadee792-77b3-461d-b16a-b1e803e2fe76
X-iAdvize-Delivery: zdsse792-77b3-461d-b16a-aae803e2fe9w
```
https://github.com/iadvize/connectors-webhook-api-service/pull/23
https://github.com/iadvize/connectors-webhook-emitter-job/pull/18
https://github.com/iadvize/connectors-app/pull/181
=> INT-346 - Sign request

Documentation.md
Section indicators and Stings of Conversation history
=> Update Documentation for lisibility

Documentation.md
> Ticket link [RDMSG-558](https://iadvize.atlassian.net/browse/RDMSG-558)
=> RDMSG-558 - DOC - Add parent list field to a specific group

Documentation.md
=> feix: set SSO url to https scheme

Documentation.md
=> fix: Tables & history example

Documentation.md
> Ticket link [INT-750](https://iadvize.atlassian.net/browse/INT-750)
add login, logout, chat start, call started
https://github.com/iadvize/chef-repo/pull/859
https://github.com/iadvize/system-amqp-middleware-service/pull/33
https://github.com/iadvize/connectors-webhook-collector-job/pull/21
https://github.com/iadvize/connectors-webhook-emitter-job/pull/19
=> INT-750 - Add conversation.started, login and logout events

Documentation.md
=> IDZ-9571 - Update Live Documentation

Documentation.md
=> Update SSO and delete SDK Documentation

Documentation.md
=> Documentation - Fix statistic indicators display

Documentation.md
=> add secret token app doc

Documentation.md
=> Update documentation Link

Documentation.md
=> fix: Change interaction name

Documentation.md
> Ticket link [INT-858](https://iadvize.atlassian.net/browse/INT-858)
Add transfer event
=> INT-858 - add transfer event

Documentation.md
=> fix : statistic

Documentation.md
https://iadvize.atlassian.net/browse/INT-832
=> Fix interaction

Documentation.md
> Ticket link [INT-927](https://iadvize.atlassian.net/browse/INT-927)
Retry webhook
https://developers.iadvize.com/documentation/test/INT-927-RetryOnWebhook#webhook-retry-management
=> INT-927 - retry webhook

Documentation.md
> Ticket link [INT-900](https://iadvize.atlassian.net/browse/INT-900)
View in production context: https://developers.iadvize.com/documentation/test/INT-900-addStepValidationDocumentation#app-authentication
=> feat: Add / Modify "step interaction" documentation

Documentation.md
> Ticket link [RDMSG-930](https://iadvize.atlassian.net/browse/RDMSG-930)
=> RDMSG-930 - update transactions documentation 

Documentation.md
=> wording correction

Documentation.md
> Ticket link [RDMSG-1160](https://iadvize.atlassian.net/browse/RDMSG-1160)
=> RDMSG-1160 - FEAT -  add multiple id filter on operator ressource

Documentation.md
=> Update Webhook documentation

Documentation.md
> Ticket link [INT-1134](https://iadvize.atlassian.net/browse/INT-1134)
Add documentation
=> INT-1134 - Add idOperator query parameter to interaction

Documentation.md, README.md
> Ticket link [INT-1155](https://iadvize.atlassian.net/browse/INT-1155)
Add graphql documentaiton
=> INT-1155 - Add graphql link, and delete api name from webhook

Documentation.md
=> Fix webhooks menu conflict

Documentation.md
> Ticket link [INT-1175](https://iadvize.atlassian.net/browse/INT-1175)
=> INT-1175 - Add graphql authentication section

Documentation.md
Add example query for GraphQL
https://developers.iadvize.com/documentation/test/addExampleForGraphQL#example
=> doc(graphql): add example

Documentation.md
=> Int 1276 bot

Documentation.md
> Ticket link [INT-1264](https://iadvize.atlassian.net/browse/INT-1264)
=> INT-1264 - Add SELECT type doc on conversation closing form plugin

Documentation.md
=> Add a conversation flow example

Documentation.md
Les attributs createdAt et updatedAt des endpoints conversations et conversations/.../messages sont required
=> conversation createdAt and updatedAt required

Documentation.md
=> remove bad information on webhook

Documentation.md
=> improve example bot

Documentation.md
https://github.com/iadvize/core-admin-app/pull/1075
=> Int 1427 int 1430 add timezone and lang to website resource

Documentation.md
> Ticket link [INT-1454](https://iadvize.atlassian.net/browse/INT-1454)
=> INT-1454 - Add action type

Documentation.md
=> fix: align doc with API return

Documentation.md
=> fix: datetime format

Documentation.md
> [Ticket link](https://iadvize.atlassian.net/browse/NT-1530)
=> INT-1530: add doc for v2.conversation.pushed

Documentation.md
> [Ticket link](https://iadvize.atlassian.net/browse/INT-1607)
=> INT-1607: add section about healthcheck endpoint

Documentation.md
> Ticket link [INT-1629](https://iadvize.atlassian.net/browse/INT-1629)
To review: 
- https://developers.iadvize.com/documentation/test/INT-1629-add-v2-conversation-closed
- https://github.com/iadvize/documentation/pull/111/files?short_path=c8937bd#diff-c8937bdc87239cee6090648dacad2027
=> INT-1629 - Add v2.conversation.closed event

Documentation.md
NO-TICKET 
Json schemas expose variables as required.
=> NO-TICKET - Bot conversation, variables are required in jsonschema

Documentation.md
Reverts iadvize/documentation#115
=> Revert "NO-TICKET - Content-type for quick-replies"

Documentation.md
Reverts iadvize/documentation#116
=> Revert "Revert "NO-TICKET - Content-type for quick-replies""

Documentation.md
> [Ticket link](https://iadvize.atlassian.net/browse/INT-1653)
=> INT-1653: non empty options doc

Documentation.md
> [Ticket link](https://iadvize.atlassian.net/browse/INT-1566)
=> INT-1566: Document new integer and decimal fields in closing form

Documentation.md, Navigation.md
> Ticket link [INT-1686](https://iadvize.atlassian.net/browse/INT-1686)
INT-1686 - Add SDK navigation and content
=> INT-1686 - Add SDK navigation and content

Documentation.md
> Ticket link [INT-1660](https://iadvize.atlassian.net/browse/INT-1660)
=> INT-1660 - Add json schemas links in plugins sections

Documentation.md, Navigation.md
=> Sdemonti patch 3

docs/webhooks.md
=> NO-TICKET: remove invalid annotations

docs/rest-api.md
> Ticket link [INT-1724](https://iadvize.atlassian.net/browse/INT-1724)
API REST, add website_list filter on operator resource
https://github.com/iadvize/core-admin-app/compare/INT-1724-add-website-list-filter-for-operator
=> INT-1724 - API REST, add website_list filter on operator resource

docs/building-your-bot-on-iadvize.md
=> Typo in bot conversation flow

docs/building-your-bot-on-iadvize.md
=> Fix parameter type in strategies route

docs/rest-api.md
> Ticket link [INT-1770](https://iadvize.atlassian.net/browse/INT-1770)
=> Add premium filed to client ressource

docs/building-your-bot-on-iadvize.md
=> fix: product-offer enum

docs/building-your-bot-on-iadvize.md
=> doc(bot): typo

docs/graphql-api.md
=> doc(graphQL): better examples

Navigation.md, docs/single-sign-on.md
=> Delete SSO dest parameter in documentation

docs/graphql-api.md
> Ticket link [INT-1837](https://iadvize.atlassian.net/browse/INT-1837)
=> INT-1837 - Add example for clients requests

Navigation.md, docs/graphql-api.md
> Ticket link [INT-1842](https://iadvize.atlassian.net/browse/INT-1842)
Add link to the integrated tool in developers platform
=> INT-1842 - Add graphiql tool link

docs/building-your-bot-on-iadvize.md
=> doc: specify the timeout delay when replying to a user

docs/building-your-bot-on-iadvize.md
=> doc: Replace : warning : by ⚠️

docs/building-your-bot-on-iadvize.md
=> doc: increase timeout delay for bot responses

docs/rest-api.md
=> doc: Remove useless filter and fix formating

docs/javascript-callbacks.md
=> doc: Update onMessageReceived & fix nested items

Navigation.md, docs/building-your-bot-on-iadvize.md
> Ticket link [INT-1791](https://iadvize.atlassian.net/browse/INT-1791)
Add proactive bot documentation
replace https://github.com/iadvize/documentation/pull/121
=> INT-2031 - Add proactive bot documentation

CODEOWNERS
=> misc(github): update codeowners

docs/javascript-callbacks.md
=> [doc] New data in onChatStarted callback

docs/javascript-callbacks.md
=> [doc] Remove undocumented and useless property startedBy

docs/javascript-callbacks.md
=> [doc] Add precision on onChatDisplayed callback

docs/building-your-bot-on-iadvize.md
=> [doc] Add precision for the replies array in POST conversation

docs/graphql-api.md
=> Remove duplicate curl example

Navigation.md
=> [doc] Remove blank lines

docs/graphql-api.md
=> [doc] Add graphql token lifetime info

docs/single-sign-on.md
=> [doc] Specify SSO url depending on the platform

docs/build-apps.md
=> [doc] Add max length limit for closing form field

docs/webhooks.md
=> doc: mark the old satisfaction webhook as deprecated

docs/graphql-api.md
=> doc: Add rate limit policy on graphql authentication

docs/rest-api.md
=> doc: remove delete, put and post operations except on operator

docs/building-your-bot-on-iadvize.md
=> doc: Update FAQ and Troubleshooting sections

docs/build-apps.md
> Ticket link [INT-2393](https://iadvize.atlassian.net/browse/INT-2393)
Closing form, increase limit for closing form response to 1024 characters
Example:
https://github.com/iadvize/connectors-app/pull/543
https://github.com/iadvize/core-desk-app/pull/3395
=> INT-2393 - Closing form, increase limit for closing form response to 1024 characters

Navigation.md
=> doc: deprecate call meeting

docs/webhooks.md
> Ticket link [INT-2420](https://iadvize.atlassian.net/browse/INT-2420)
=> INT-2420 Update documentation for adding satisfaction.answered event

docs/building-your-bot-on-iadvize.md
=> doc: explain how to get a routing rule availabilty

docs/rest-api.md
> Ticket link [INT-2570](https://iadvize.atlassian.net/browse/INT-2570)
=> feat(REST/transaction): mention the maximum duration

docs/rest-api.md
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>
=> Added chat_to_video documentation

docs/build-apps.md
> Ticket link [OGDK-3153](https://iadvize.atlassian.net/browse/OGDK-3153)
=> OGDK-3153: add doc for enable operators/experts checkboxes

docs/building-your-bot-on-iadvize.md
idQuickReply are now optional and they are useless. To avoid confusion it is removed from the doc.
=> doc: remove idQuickReply

docs/building-your-bot-on-iadvize.md
Markdown is not supported in the same way on all social channels
=> doc: warning markdown on social channels

docs/building-your-bot-on-iadvize.md
10s timeout on all endpoint except for conversation-first-messages (2s)
=> doc: timeout warning

docs/build-apps.md
Update lib version for mobile apps.
=> doc: update lib version for mobile apps

docs/build-apps.md
> Ticket link [OGDK-3394](https://iadvize.atlassian.net/browse/OGDK-3394)
=> OGDK-3394: add documentation for cpa context adn authentication

docs/build-apps.md
Fix white background in CPA code examples.
=> NOTICKET: fix white background

docs/webhooks.md
> Ticket link [INT-2715](https://iadvize.atlassian.net/browse/INT-2715)
Add visitor id in conversation.pushed and closed webhook.
https://github.com/iadvize/connectors-webhook-collector-job/pull/99
https://github.com/iadvize/connectors-webhook-emitter-job/pull/80
=> INT-2715: Add visitor id in conversation.pushed and closed webhook

docs/rest-api.md
NO-TICKET - API Rest, operator ressource, add missing email filter
=> NO-TICKET - API Rest, operator ressource, add missing email filter

docs/rest-api.md
add precision on Transations REST API on timing
=> add precision on Transations REST API

docs/webhooks.md
> Ticket link [](https://iadvize.atlassian.net/browse/INT-2998)
=> INT-2998 Webhooks: add custom question

docs/javascript-web-sdk.md
> Ticket link [MSG-5699](https://iadvize.atlassian.net/browse/MSG-5699)
JS Web SDK update
=> MSG-5699 - fix: JS Web SDK update

docs/building-your-bot-on-iadvize.md
=> NOTICKET: fix idBot documentation
